source 'https://github.com/qinzhongzeng55/QZZSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QZZAPIsKit_Example' do
  pod 'QZZAPIsKit', :path => '../'
  pod 'QZZToolsKit'
  pod 'AFNetworking'
  target 'QZZAPIsKit_Tests' do
    inherit! :search_paths

    
  end
end
